server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Problemes/springcloud-config-repo  #{application}
  application:
    name: thomas

encrypt:
  key: secrets

