server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${server.port}} #${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

MICROSERVICE-PROVIDER-USER: #取代ribbon注解配置，使用配置文件配置客户端负载均衡策略方便快捷
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule