server:
  port: 9000


eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
zuul:
  routes:
    MICROSERVICE-PROVIDER-USER: /user/**
    movie:
      path: /movie/**
#      url: http://localhost:8200/
      serviceId: microservice-consumer-movie-feign-hystrix
#  ignored-services: microservice-consumer-movie-feign-hystrix

ribbon:
  eureka:
    enabled: false

MICROSERVICE-PROVIDER-USER:  # 手动配置ribbon 客户端负载均衡，先禁用 ribbon的eureka使用
  ribbon:
    listOfServers: http://localhost:7901, http://localhost:7902



spring:
  application:
    name: getway-zuul

