server:
  port: 8200
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${server.port}} #${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000  #hystrix 超时策略，略长于ribbon的超时时长 * 尝试次数。
feign.hystrix.enabled: true #全局feign 的hystrix支持设置

logging:
  level:
    com.hr.cloud.microserviceconsumermoviefeign.stroes.StoreClient: DEBUG