server:
  port: 8020
spring:
  application:
    name: microservice-consumer-movie-ribbon-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${server.port}} #${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000