server:
  port: 8100
spring:
  application:
    name: microservice-consumer-movie-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${server.port}} #${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging:
  level:
    com.hr.cloud.microserviceconsumermoviefeign.stroes.StoreClient: DEBUG